# Generated by Django 5.2.14 on 2026-05-29 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtag', models.CharField(max_length=64)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('analysed_resolution', models.FloatField(blank=True, null=True)),
                ('high_resolution', models.FloatField(blank=True, null=True)),
                ('low_resolution', models.FloatField(blank=True, null=True)),
                ('r_free', models.FloatField(blank=True, null=True)),
                ('r_work', models.FloatField(blank=True, null=True)),
                ('map_uncertainty', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['dtag'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('source_root', models.CharField(max_length=1024)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_num', models.IntegerField()),
                ('site_num', models.IntegerField(blank=True, null=True)),
                ('event_fraction', models.FloatField(blank=True, null=True)),
                ('bdc', models.FloatField(blank=True, null=True)),
                ('z_peak', models.FloatField(blank=True, null=True)),
                ('z_mean', models.FloatField(blank=True, null=True)),
                ('cluster_size', models.IntegerField(blank=True, null=True)),
                ('map_resolution', models.FloatField(blank=True, null=True)),
                ('xyz_centroid', models.JSONField(default=list)),
                ('xyz_peak', models.JSONField(default=list)),
                ('decision', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('hit', 'Hit'), ('no_hit', 'No hit'), ('ambiguous', 'Ambiguous')], default='unreviewed', max_length=16)),
                ('confidence', models.CharField(blank=True, default='', max_length=32)),
                ('comment', models.TextField(blank=True, default='')),
                ('inspected_by', models.CharField(blank=True, default='', max_length=255)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inspect_api.dataset')),
            ],
            options={
                'ordering': ['dataset__dtag', 'event_num'],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('structure', 'Structure (coords)'), ('data_mtz', 'Reflection data (MTZ)'), ('output_mtz', 'Output / Z-map MTZ'), ('event_map', 'Event map'), ('ligand', 'Ligand dictionary')], max_length=16)),
                ('relpath', models.CharField(max_length=1024)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='inspect_api.dataset')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='inspect_api.event')),
            ],
            options={
                'ordering': ['dataset__dtag', 'kind'],
            },
        ),
        migrations.AddField(
            model_name='dataset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='inspect_api.project'),
        ),
        migrations.CreateModel(
            name='Shell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('resolution_high', models.FloatField(blank=True, null=True)),
                ('resolution_low', models.FloatField(blank=True, null=True)),
                ('map_resolution', models.FloatField(blank=True, null=True)),
                ('map_uncertainty', models.FloatField(blank=True, null=True)),
                ('n_train', models.IntegerField(default=0)),
                ('n_test', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shells', to='inspect_api.project')),
            ],
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('dataset', 'event_num'), name='uniq_dataset_event'),
        ),
        migrations.AddConstraint(
            model_name='dataset',
            constraint=models.UniqueConstraint(fields=('project', 'dtag'), name='uniq_project_dtag'),
        ),
    ]
