# Generated by Django 5.2.14 on 2026-05-29 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspect_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artifact',
            options={'ordering': ['kind', 'relpath']},
        ),
        migrations.AddField(
            model_name='artifact',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='inspect_api.project'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='inspect_api.dataset'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='kind',
            field=models.CharField(choices=[('structure', 'Structure (coords)'), ('data_mtz', 'Reflection data (MTZ)'), ('output_mtz', 'Output / Z-map MTZ'), ('event_map', 'Event map'), ('ligand', 'Ligand dictionary'), ('report_html', 'HTML report')], max_length=20),
        ),
    ]
