# Generated by Django 5.2.14 on 2026-05-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspect_api', '0002_alter_artifact_options_artifact_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='interesting',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
