# Generated by Django 5.2.14 on 2026-05-31 10:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspect_api', '0003_event_interesting_event_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artifact',
            name='origin',
            field=models.CharField(choices=[('imported', 'Imported (from PanDDA output)'), ('built', 'Built (human, e.g. ligand placed in Moorhen)'), ('refined', 'Refined (job output, e.g. giant.quick_refine)')], default='imported', max_length=16),
        ),
        migrations.AddField(
            model_name='artifact',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived', to='inspect_api.artifact'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='current_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inspect_api.artifact'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='inputs_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='current_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inspect_api.artifact'),
        ),
        migrations.AddField(
            model_name='event',
            name='inputs_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(max_length=64)),
                ('spec', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('runner_handle', models.CharField(blank=True, default='', max_length=255)),
                ('log_relpath', models.CharField(blank=True, default='', max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='inspect_api.dataset')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='inspect_api.event')),
                ('output_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inspect_api.artifact')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='artifact',
            name='produced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outputs', to='inspect_api.job'),
        ),
    ]
