# Generated by Django 5.2.14 on 2026-05-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspect_api', '0004_artifact_created_at_artifact_origin_artifact_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='contents',
            field=models.TextField(blank=True, default=''),
        ),
    ]
