# Generated by Django 5.2.14 on 2026-05-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspect_api', '0006_dataset_ligand_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='build_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='optimal_contour',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='rscc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='kind',
            field=models.CharField(choices=[('structure', 'Structure (coords)'), ('data_mtz', 'Reflection data (MTZ)'), ('output_mtz', 'Output / Z-map MTZ'), ('event_map', 'Event map'), ('ligand', 'Ligand dictionary'), ('ligand_pose', 'Autobuilt ligand pose (event)'), ('report_html', 'HTML report')], max_length=20),
        ),
    ]
