# Generated by Django 5.2.14 on 2026-05-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspect_api', '0007_event_build_score_event_optimal_contour_event_rscc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pose_merged',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
