# Generated by Django 5.2.14 on 2026-06-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspect_api', '0009_dataset_current_sf'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='map_columns',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
