# Generated by Django 4.2.30 on 2026-06-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspect_api', '0010_artifact_map_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='inspected_by_oid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
