# Generated by Django 4.2.30 on 2026-06-06 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspect_api', '0011_event_inspected_by_oid'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=255)),
                ('share_path', models.CharField(max_length=1024)),
                ('out_dir', models.CharField(blank=True, default='', max_length=1024)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('provisioning', 'Provisioning'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('failure_mode', models.CharField(blank=True, default='', max_length=64)),
                ('failure_message', models.CharField(blank=True, default='', max_length=512)),
                ('failure_detail', models.TextField(blank=True, default='')),
                ('runner_handle', models.CharField(blank=True, default='', max_length=255)),
                ('log_stream_url', models.CharField(blank=True, default='', max_length=1024)),
                ('shell_progress', models.CharField(blank=True, default='', max_length=32)),
                ('triggered_by_oid', models.CharField(blank=True, max_length=255, null=True)),
                ('idempotency_key', models.CharField(max_length=80, unique=True)),
                ('sizing_hint', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('parent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='inspect_api.run')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='inspect_api.project')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
