# Generated by Django 4.2.30 on 2026-06-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspect_api', '0013_rename_run_shell_progress_to_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='idempotency_key',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
