# Generated by Django 4.2.30 on 2026-06-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspect_api', '0014_alter_run_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='params',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
