# Generated by Django 4.2.30 on 2026-06-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspect_api', '0015_run_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='detection_centroid',
            field=models.JSONField(default=list),
        ),
    ]
