# Generated by Django 4.2.30 on 2026-06-09 15:16

from django.db import migrations, models
import django.db.models.deletion


def _wipe_historical_data(apps, schema_editor):
    """Phase C moves the decision/review fields off Event onto Finding; by the
    blat-all-historical-data decision we wipe rather than backfill, so events
    are re-ingested and re-associated to freshly-seeded Findings (no event left
    with a null finding). Projects are kept. Irreversible."""
    for name in ("Artifact", "Job", "Event", "Shell", "Dataset", "Run"):
        apps.get_model("inspect_api", name).objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inspect_api', '0017_rundataset_remove_event_uniq_dataset_event_and_more'),
    ]

    operations = [
        migrations.RunPython(
            _wipe_historical_data, migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='event',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='event',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='event',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='event',
            name='inspected_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='inspected_by',
        ),
        migrations.RemoveField(
            model_name='event',
            name='inspected_by_oid',
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centroid', models.JSONField(default=list)),
                ('decision', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('hit', 'Hit'), ('no_hit', 'No hit'), ('ambiguous', 'Ambiguous')], default='unreviewed', max_length=16)),
                ('confidence', models.CharField(blank=True, default='', max_length=32)),
                ('comment', models.TextField(blank=True, default='')),
                ('inspected_by', models.CharField(blank=True, default='', max_length=255)),
                ('inspected_by_oid', models.CharField(blank=True, max_length=255, null=True)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='inspect_api.dataset')),
            ],
            options={
                'ordering': ['dataset__dtag', 'id'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='finding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='inspect_api.finding'),
        ),
    ]
