# Generated by Django 4.2.30 on 2026-06-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspect_api', '0018_remove_event_comment_remove_event_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source_managed',
            field=models.BooleanField(default=False),
        ),
    ]
